version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - bundle_path:/usr/local/bundle
    command: script/puma
    env_file: ".env"
    environment:
      - HOME=/app
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      - assets
    links:
      - assets
    # user: ${CURRENT_UID}
  assets:
    image: node:alpine
    env_file: ".env"
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    expose:
      - "8080"
    command: "npm start"
  db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf"
      - "./postgres/data:/var/lib/postgresql/data:delegated"
    command: "postgres -c config_file=/usr/local/etc/postgres/postgres.conf"
    # ports:
    #   - "5432:5432"
volumes:
  bundle_path:
  node_modules:
